version: '3'
services:
  db:
    image: postgres:9.4.5
    container_name: e-commerce-db
    volumes: 
      - $PWD/db_data:/var/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  backend:
    image: alayahamza/e-commerce-back
    container_name: e-commerce-backend
    ports: 
      - "8080:8080"
    depends_on:
      - db
  frontend:
    image: alayahamza/e-commerce-front
    container_name: e-commerce-frontend
    ports: 
      - "80:80"
    depends_on: 
      - backend
